/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author mattj
 */
public class BankGUI extends javax.swing.JFrame {

    /**
     * Creates new form BankGUI
     */
    public BankGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        homePage = new javax.swing.JPanel();
        welcomeTxt = new javax.swing.JLabel();
        depositPage = new javax.swing.JPanel();
        lblDeposit = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        depsoitBtn = new javax.swing.JButton();
        acctNumberDeposit = new javax.swing.JTextField();
        depositAmt = new javax.swing.JTextField();
        withdrawPage = new javax.swing.JPanel();
        lblWithdraw = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        acctNumberWithdraw = new javax.swing.JTextField();
        withdrawAmt = new javax.swing.JTextField();
        withdrawBtn = new javax.swing.JButton();
        transferPage = new javax.swing.JPanel();
        lblTransfer = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        acctNumTransferFrom = new javax.swing.JTextField();
        acctNumTransferTo = new javax.swing.JTextField();
        transferAmt = new javax.swing.JTextField();
        makePaymentPage = new javax.swing.JPanel();
        lblMakePayment = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        paymentAmount = new javax.swing.JTextField();
        makePaymentBtn = new javax.swing.JButton();
        acctNumberMakePayment = new javax.swing.JTextField();
        addAcctPage = new javax.swing.JPanel();
        lblAddAcct = new javax.swing.JLabel();
        deleteAcctPage = new javax.swing.JPanel();
        lblRemoveAcct = new javax.swing.JLabel();
        acctNumberRemoveAcct = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        removeAcctBtn = new javax.swing.JToggleButton();
        acctDetailPage = new javax.swing.JPanel();
        lblAcctDetails = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        acctNumberViewDetails = new javax.swing.JTextField();
        jScrollPane = new javax.swing.JScrollPane();
        acctDetailsTxtBox = new javax.swing.JTextArea();
        ViewAcctDetailsBtn = new javax.swing.JButton();
        bankDetailsPage = new javax.swing.JPanel();
        lblBankDetails = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bankDetailsTxtBox = new javax.swing.JTextArea();
        bankMenuBar = new javax.swing.JMenuBar();
        menuTransactions = new javax.swing.JMenu();
        menuDeposit = new javax.swing.JMenuItem();
        menuWithdraw = new javax.swing.JMenuItem();
        menuTransfer = new javax.swing.JMenuItem();
        menuPayments = new javax.swing.JMenu();
        menuMakePayment = new javax.swing.JMenuItem();
        menuAccts = new javax.swing.JMenu();
        menuCreateAcct = new javax.swing.JMenuItem();
        menuRemoveAcct = new javax.swing.JMenuItem();
        menuViewAcct = new javax.swing.JMenuItem();
        menuBank = new javax.swing.JMenu();
        menuBankDetails = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Page");
        setName("BankGUI"); // NOI18N

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        welcomeTxt.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        welcomeTxt.setForeground(new java.awt.Color(2, 3, 2));
        welcomeTxt.setText("Welcome");

        javax.swing.GroupLayout homePageLayout = new javax.swing.GroupLayout(homePage);
        homePage.setLayout(homePageLayout);
        homePageLayout.setHorizontalGroup(
            homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePageLayout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(welcomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
        );
        homePageLayout.setVerticalGroup(
            homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePageLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(welcomeTxt)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        jLayeredPane1.add(homePage, "card2");

        depositPage.setMinimumSize(new java.awt.Dimension(10, 10));

        lblDeposit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblDeposit.setText("Deposit");
        lblDeposit.setOpaque(true);

        jLabel5.setText("Please enter the account number you would like to deposit to:");
        jLabel5.setOpaque(true);

        jLabel6.setText("Please enter the amount you would like to deposit:");
        jLabel6.setOpaque(true);

        depsoitBtn.setText("Deposit");

        acctNumberDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acctNumberDepositActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout depositPageLayout = new javax.swing.GroupLayout(depositPage);
        depositPage.setLayout(depositPageLayout);
        depositPageLayout.setHorizontalGroup(
            depositPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositPageLayout.createSequentialGroup()
                .addGroup(depositPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(depositPageLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(depositPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(depositPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(acctNumberDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(depositAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(depositPageLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(depsoitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(depositPageLayout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(lblDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        depositPageLayout.setVerticalGroup(
            depositPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(depositPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(acctNumberDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(depositPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(depositAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(depsoitBtn)
                .addGap(44, 44, 44))
        );

        jLayeredPane1.add(depositPage, "card3");

        lblWithdraw.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblWithdraw.setText("Withdraw");

        jLabel9.setText("Please enter the account number you would like to withdraw from:");

        jLabel10.setText("Please enter the amount you would like to withdraw:");

        acctNumberWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acctNumberWithdrawActionPerformed(evt);
            }
        });

        withdrawBtn.setText("Withdraw");

        javax.swing.GroupLayout withdrawPageLayout = new javax.swing.GroupLayout(withdrawPage);
        withdrawPage.setLayout(withdrawPageLayout);
        withdrawPageLayout.setHorizontalGroup(
            withdrawPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawPageLayout.createSequentialGroup()
                .addGroup(withdrawPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(withdrawPageLayout.createSequentialGroup()
                        .addGroup(withdrawPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(withdrawPageLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(withdrawPageLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56)
                        .addGroup(withdrawPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(withdrawAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acctNumberWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(withdrawPageLayout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(lblWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(withdrawPageLayout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(withdrawBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 158, Short.MAX_VALUE))
        );
        withdrawPageLayout.setVerticalGroup(
            withdrawPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWithdraw)
                .addGap(28, 28, 28)
                .addGroup(withdrawPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(acctNumberWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(withdrawPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(withdrawAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(withdrawBtn)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jLayeredPane1.add(withdrawPage, "card4");

        lblTransfer.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTransfer.setText("Transfer Funds");

        jLabel12.setText("Please enter the account number you would like to transfer from:");

        jLabel13.setText("Please enter the account number of the account you would like to transfer to:");

        jLabel14.setText("Enter the amount you would like to transfer:");

        jButton2.setText("Transfer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        acctNumTransferFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acctNumTransferFromActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout transferPageLayout = new javax.swing.GroupLayout(transferPage);
        transferPage.setLayout(transferPageLayout);
        transferPageLayout.setHorizontalGroup(
            transferPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transferPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transferPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transferPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(acctNumTransferTo)
                        .addComponent(transferAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(acctNumTransferFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(transferPageLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(lblTransfer)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transferPageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(271, 271, 271))
        );
        transferPageLayout.setVerticalGroup(
            transferPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTransfer)
                .addGap(18, 18, 18)
                .addGroup(transferPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transferPageLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(24, 24, 24)
                        .addGroup(transferPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(acctNumTransferTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(transferPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(transferAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(acctNumTransferFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButton2)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLayeredPane1.add(transferPage, "card5");

        lblMakePayment.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblMakePayment.setText("Make a Payment");

        jLabel16.setText("Please enter the account number you would like to make a payment to:");

        jLabel17.setText("Please enter the amount you would like to pay:");

        makePaymentBtn.setText("Make Payment");

        acctNumberMakePayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acctNumberMakePaymentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout makePaymentPageLayout = new javax.swing.GroupLayout(makePaymentPage);
        makePaymentPage.setLayout(makePaymentPageLayout);
        makePaymentPageLayout.setHorizontalGroup(
            makePaymentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, makePaymentPageLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblMakePayment)
                .addGap(228, 228, 228))
            .addGroup(makePaymentPageLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(makePaymentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(makePaymentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paymentAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(acctNumberMakePayment))
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, makePaymentPageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(makePaymentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(272, 272, 272))
        );
        makePaymentPageLayout.setVerticalGroup(
            makePaymentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(makePaymentPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMakePayment)
                .addGap(26, 26, 26)
                .addGroup(makePaymentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(acctNumberMakePayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(makePaymentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(paymentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(makePaymentBtn)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jLayeredPane1.add(makePaymentPage, "card6");

        lblAddAcct.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblAddAcct.setText("Add an Account");

        javax.swing.GroupLayout addAcctPageLayout = new javax.swing.GroupLayout(addAcctPage);
        addAcctPage.setLayout(addAcctPageLayout);
        addAcctPageLayout.setHorizontalGroup(
            addAcctPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addAcctPageLayout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addComponent(lblAddAcct)
                .addGap(245, 245, 245))
        );
        addAcctPageLayout.setVerticalGroup(
            addAcctPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addAcctPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddAcct)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        jLayeredPane1.add(addAcctPage, "card7");

        lblRemoveAcct.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblRemoveAcct.setText("Remove an Account");

        acctNumberRemoveAcct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acctNumberRemoveAcctActionPerformed(evt);
            }
        });

        jLabel20.setText("Please enter the account number of the account you would like to remove:");

        removeAcctBtn.setText("Remove Account");

        javax.swing.GroupLayout deleteAcctPageLayout = new javax.swing.GroupLayout(deleteAcctPage);
        deleteAcctPage.setLayout(deleteAcctPageLayout);
        deleteAcctPageLayout.setHorizontalGroup(
            deleteAcctPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteAcctPageLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(acctNumberRemoveAcct, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
            .addGroup(deleteAcctPageLayout.createSequentialGroup()
                .addGroup(deleteAcctPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deleteAcctPageLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(lblRemoveAcct))
                    .addGroup(deleteAcctPageLayout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(removeAcctBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deleteAcctPageLayout.setVerticalGroup(
            deleteAcctPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteAcctPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRemoveAcct)
                .addGap(40, 40, 40)
                .addGroup(deleteAcctPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(acctNumberRemoveAcct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(removeAcctBtn)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jLayeredPane1.add(deleteAcctPage, "card8");

        lblAcctDetails.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblAcctDetails.setText("View Account Details");

        jLabel22.setText("Please enter the account number of the account you would like to see the details of:");

        acctNumberViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acctNumberViewDetailsActionPerformed(evt);
            }
        });

        acctDetailsTxtBox.setEditable(false);
        acctDetailsTxtBox.setColumns(20);
        acctDetailsTxtBox.setRows(5);
        acctDetailsTxtBox.setText("Account details...");
        jScrollPane.setViewportView(acctDetailsTxtBox);

        ViewAcctDetailsBtn.setText("View Account Details");
        ViewAcctDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAcctDetailsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout acctDetailPageLayout = new javax.swing.GroupLayout(acctDetailPage);
        acctDetailPage.setLayout(acctDetailPageLayout);
        acctDetailPageLayout.setHorizontalGroup(
            acctDetailPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(acctDetailPageLayout.createSequentialGroup()
                .addGroup(acctDetailPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(acctDetailPageLayout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(lblAcctDetails))
                    .addGroup(acctDetailPageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(acctNumberViewDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, acctDetailPageLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(acctDetailPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, acctDetailPageLayout.createSequentialGroup()
                        .addComponent(ViewAcctDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(262, 262, 262))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, acctDetailPageLayout.createSequentialGroup()
                        .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138))))
        );
        acctDetailPageLayout.setVerticalGroup(
            acctDetailPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(acctDetailPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAcctDetails)
                .addGap(18, 18, 18)
                .addGroup(acctDetailPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(acctNumberViewDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ViewAcctDetailsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
        );

        jLayeredPane1.add(acctDetailPage, "card9");

        lblBankDetails.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblBankDetails.setText("View Bank Details");

        bankDetailsTxtBox.setEditable(false);
        bankDetailsTxtBox.setColumns(20);
        bankDetailsTxtBox.setRows(5);
        jScrollPane2.setViewportView(bankDetailsTxtBox);

        javax.swing.GroupLayout bankDetailsPageLayout = new javax.swing.GroupLayout(bankDetailsPage);
        bankDetailsPage.setLayout(bankDetailsPageLayout);
        bankDetailsPageLayout.setHorizontalGroup(
            bankDetailsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bankDetailsPageLayout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addGroup(bankDetailsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bankDetailsPageLayout.createSequentialGroup()
                        .addComponent(lblBankDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(218, 218, 218))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bankDetailsPageLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))))
        );
        bankDetailsPageLayout.setVerticalGroup(
            bankDetailsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bankDetailsPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBankDetails)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLayeredPane1.add(bankDetailsPage, "card10");

        menuTransactions.setText("Transactions");

        menuDeposit.setText("Deposit");
        menuDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDepositActionPerformed(evt);
            }
        });
        menuTransactions.add(menuDeposit);

        menuWithdraw.setText("Withdraw");
        menuWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuWithdrawActionPerformed(evt);
            }
        });
        menuTransactions.add(menuWithdraw);

        menuTransfer.setText("Transfer");
        menuTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTransferActionPerformed(evt);
            }
        });
        menuTransactions.add(menuTransfer);

        bankMenuBar.add(menuTransactions);

        menuPayments.setText("Payments");

        menuMakePayment.setText("Make a Payment");
        menuMakePayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMakePaymentActionPerformed(evt);
            }
        });
        menuPayments.add(menuMakePayment);

        bankMenuBar.add(menuPayments);

        menuAccts.setText("Accounts");
        menuAccts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAcctsActionPerformed(evt);
            }
        });

        menuCreateAcct.setText("Create an Account");
        menuCreateAcct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCreateAcctActionPerformed(evt);
            }
        });
        menuAccts.add(menuCreateAcct);

        menuRemoveAcct.setText("Delete an Account");
        menuRemoveAcct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRemoveAcctActionPerformed(evt);
            }
        });
        menuAccts.add(menuRemoveAcct);

        menuViewAcct.setText("View Account Details");
        menuViewAcct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuViewAcctActionPerformed(evt);
            }
        });
        menuAccts.add(menuViewAcct);

        bankMenuBar.add(menuAccts);

        menuBank.setText("Bank");

        menuBankDetails.setText("View Bank Details");
        menuBankDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBankDetailsActionPerformed(evt);
            }
        });
        menuBank.add(menuBankDetails);

        bankMenuBar.add(menuBank);

        setJMenuBar(bankMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void menuTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTransferActionPerformed
        // TODO add your handling code here:
        jLayeredPane1.removeAll();
        jLayeredPane1.add(transferPage);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
        
    }//GEN-LAST:event_menuTransferActionPerformed

    private void acctNumberDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acctNumberDepositActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acctNumberDepositActionPerformed

    private void menuDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDepositActionPerformed
        // TODO add your handling code here:
        jLayeredPane1.removeAll();
        jLayeredPane1.add(depositPage);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
    }//GEN-LAST:event_menuDepositActionPerformed

    private void acctNumberWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acctNumberWithdrawActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acctNumberWithdrawActionPerformed

    private void menuWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuWithdrawActionPerformed
        // TODO add your handling code here:
        jLayeredPane1.removeAll();
        jLayeredPane1.add(withdrawPage);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
    }//GEN-LAST:event_menuWithdrawActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void acctNumTransferFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acctNumTransferFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acctNumTransferFromActionPerformed

    private void acctNumberMakePaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acctNumberMakePaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acctNumberMakePaymentActionPerformed

    private void menuMakePaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMakePaymentActionPerformed
        // TODO add your handling code here:
        jLayeredPane1.removeAll();
        jLayeredPane1.add(makePaymentPage);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
    }//GEN-LAST:event_menuMakePaymentActionPerformed

    private void acctNumberRemoveAcctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acctNumberRemoveAcctActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acctNumberRemoveAcctActionPerformed

    private void menuCreateAcctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCreateAcctActionPerformed
        // TODO add your handling code here:
        jLayeredPane1.removeAll();
        jLayeredPane1.add(addAcctPage);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
    }//GEN-LAST:event_menuCreateAcctActionPerformed

    private void menuRemoveAcctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRemoveAcctActionPerformed
        // TODO add your handling code here:
        jLayeredPane1.removeAll();
        jLayeredPane1.add(deleteAcctPage);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
    }//GEN-LAST:event_menuRemoveAcctActionPerformed

    private void acctNumberViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acctNumberViewDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acctNumberViewDetailsActionPerformed

    private void ViewAcctDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAcctDetailsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewAcctDetailsBtnActionPerformed

    private void menuAcctsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAcctsActionPerformed
        // TODO add your handling code here:
        jLayeredPane1.removeAll();
        jLayeredPane1.add(acctDetailPage);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
    }//GEN-LAST:event_menuAcctsActionPerformed

    private void menuBankDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBankDetailsActionPerformed
        // TODO add your handling code here:
        jLayeredPane1.removeAll();
        jLayeredPane1.add(bankDetailsPage);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
        //display bank info in the textbox
    }//GEN-LAST:event_menuBankDetailsActionPerformed

    private void menuViewAcctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuViewAcctActionPerformed
        // TODO add your handling code here:
        jLayeredPane1.removeAll();
        jLayeredPane1.add(acctDetailPage);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
    }//GEN-LAST:event_menuViewAcctActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ViewAcctDetailsBtn;
    private javax.swing.JPanel acctDetailPage;
    private javax.swing.JTextArea acctDetailsTxtBox;
    private javax.swing.JTextField acctNumTransferFrom;
    private javax.swing.JTextField acctNumTransferTo;
    private javax.swing.JTextField acctNumberDeposit;
    private javax.swing.JTextField acctNumberMakePayment;
    private javax.swing.JTextField acctNumberRemoveAcct;
    private javax.swing.JTextField acctNumberViewDetails;
    private javax.swing.JTextField acctNumberWithdraw;
    private javax.swing.JPanel addAcctPage;
    private javax.swing.JPanel bankDetailsPage;
    private javax.swing.JTextArea bankDetailsTxtBox;
    private javax.swing.JMenuBar bankMenuBar;
    private javax.swing.JPanel deleteAcctPage;
    private javax.swing.JTextField depositAmt;
    private javax.swing.JPanel depositPage;
    private javax.swing.JButton depsoitBtn;
    private javax.swing.JPanel homePage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblAcctDetails;
    private javax.swing.JLabel lblAddAcct;
    private javax.swing.JLabel lblBankDetails;
    private javax.swing.JLabel lblDeposit;
    private javax.swing.JLabel lblMakePayment;
    private javax.swing.JLabel lblRemoveAcct;
    private javax.swing.JLabel lblTransfer;
    private javax.swing.JLabel lblWithdraw;
    private javax.swing.JButton makePaymentBtn;
    private javax.swing.JPanel makePaymentPage;
    private javax.swing.JMenu menuAccts;
    private javax.swing.JMenu menuBank;
    private javax.swing.JMenuItem menuBankDetails;
    private javax.swing.JMenuItem menuCreateAcct;
    private javax.swing.JMenuItem menuDeposit;
    private javax.swing.JMenuItem menuMakePayment;
    private javax.swing.JMenu menuPayments;
    private javax.swing.JMenuItem menuRemoveAcct;
    private javax.swing.JMenu menuTransactions;
    private javax.swing.JMenuItem menuTransfer;
    private javax.swing.JMenuItem menuViewAcct;
    private javax.swing.JMenuItem menuWithdraw;
    private javax.swing.JTextField paymentAmount;
    private javax.swing.JToggleButton removeAcctBtn;
    private javax.swing.JTextField transferAmt;
    private javax.swing.JPanel transferPage;
    private javax.swing.JLabel welcomeTxt;
    private javax.swing.JTextField withdrawAmt;
    private javax.swing.JButton withdrawBtn;
    private javax.swing.JPanel withdrawPage;
    // End of variables declaration//GEN-END:variables
}
